### PR TITLE
document upload fix

### LINKED ISSUE #569: BUG > Document Upload fails (M)
When attempting to upload a document to a check-in (CHECK-INS page), the upload fails with a 400 and the following error message:
```
{"message":"Error getting access token for service account: 400 Bad Request\n{\"error\":\"invalid_scope\",\"error_description\":\"Invalid OAuth scope or ID token audience provided.\"}","_links":{"self":{"href":"/services/file/e1274335-4249-4266-a5cf-b136edc66804","templated":false}}}
```

Current Behavior: The upload fails

Expected Behavior: The upload is successful and the file is associated with the check-in

### PR DESCRIPTION
**Pull request by meyerinj**
#569

### CODE REVIEW

File: server/src/main/java/com/objectcomputing/checkins/util/googleapiaccess/GoogleAccessor.java [hunk 1]
```diff
@@ -45,7 +46,7 @@ public GoogleAccessor(@Property(name = "check-ins.application.name") String appl
      */
     public Drive accessGoogleDrive() throws IOException {
 
-        String apiScope = environment.getProperty("check-ins.application.scopes.scopeForDriveApi", String.class).orElse("");
+        String apiScope = environment.getProperty("check-ins.application.google-api.scopes.scopeForDriveApi", String.class).orElse("");
```
Comment (Bagurp) [inline server/src/main/java/com/objectcomputing/checkins/util/googleapiaccess/GoogleAccessor.java:49]: Good catch. I must have broken this when I updated scope config as part of directory api story.

**Review by Bagurp — APPROVED** [review]

File: .gitignore [hunk 2]
```diff
@@ -15,5 +15,6 @@ out/
 .classpath
 node_modules
 .run
-run.bat
+**/run.bat
 *.sh
+/server/src/main/resources/secrets/*
```
Comment (mkimberlin) [inline .gitignore:20]: This shouldn't be necessary...secrets aren't a thing anymore. If you have them locally, delete them.

**Review by mkimberlin — APPROVED** [review]
