### PR TITLE
fix read all skills closes #176

### LINKED ISSUE #176: Fix Read All skills

### PR DESCRIPTION
**Pull request by hwilliams314**

### CODE REVIEW

File: server/src/main/java/com/objectcomputing/checkins/services/skills/SkillServices.java [hunk 1]
```diff
@@ -36,6 +38,12 @@ protected Skill readSkill(UUID skillId) {
 
     }
 
+    public Set<Skill> readAll() {
+        Set<Skill> actionItems = new HashSet<>();
```
Comment (bhatiam12) [inline server/src/main/java/com/objectcomputing/checkins/services/skills/SkillServices.java:42]: Please can you update variable name because I think actionItems is for action item rest service ?
