### PR TITLE
Bugfix-518/fixed sonar critial front end issues Closes #518

### LINKED ISSUE #518: FE > Fix sonar critical bugs and some refactoring (S)
- [x] Remove extra arg in killAgendaItem
- [x] Remove extra arg in killActionItem
- [x] Refactor Submit button on Checkin page

### PR DESCRIPTION
**Pull request by jahanner**

### CODE REVIEW

File: web-ui/src/components/agenda/Agenda.jsx [hunk 1]
```diff
@@ -44,9 +44,10 @@ const AgendaItems = ({ checkinId, memberName }) => {
...
         let agendaItemList =
           res.payload.data && !res.error ? res.payload.data : undefined;
-        agendaItemList.sort((a, b) => {
-          return a.priority - b.priority;
-        });
+        agendaItemList &&
+          agendaItemList.sort((a, b) => {
+            return a.priority - b.priority;
+          });
         setAgendaItems(agendaItemList);
```
Comment (mkimberlin) [inline web-ui/src/components/agenda/Agenda.jsx:51]: This makes sonar happy, but I'm not sure it's actually doing what you want. I think you probably want the null check to effect whether or not you even call `setAgendaItems`, don't you?

**Review by mkimberlin — APPROVED** [review]
Left one comment that you may want to address...but otherwise it looks fine.

**Review by Maroju100 — APPROVED** [review]

**Review by Bagurp — APPROVED** [review]

**Review by mkimberlin — APPROVED** [review]
